export const employeeConstants = {
  FETCH_EMPLOYEE_LOADING: 'FETCH_EMPLOYEE_LOADING',
  FETCH_EMPLOYEE_SUCCESS: 'FETCH_EMPLOYEE_SUCCESS',
  FETCH_EMPLOYEE_FAILURE: 'FETCH_EMPLOYEE_FAILURE',

  FETCH_PROMOTION_LOADING: 'FETCH_PROMOTION_LOADING',
  FETCH_PROMOTION_SUCCESS: 'FETCH_PROMOTION_SUCCESS',
  FETCH_PROMOTION_FAILURE: 'FETCH_PROMOTION_FAILURE',

  FETCH_LEAVE_LOADING: 'FETCH_LEAVE_LOADING',
  FETCH_LEAVE_SUCCESS: 'FETCH_LEAVE_SUCCESS',
  FETCH_LEAVE_FAILURE: 'FETCH_LEAVE_FAILURE',

  FETCH_SUSPENSION_LOADING: 'FETCH_SUSPENSION_LOADING',
  FETCH_SUSPENSION_SUCCESS: 'FETCH_SUSPENSION_SUCCESS',
  FETCH_SUSPENSION_FAILURE: 'FETCH_SUSPENSION_FAILURE',

  FETCH_TERMINATION_LOADING: 'FETCH_TERMINATION_LOADING',
  FETCH_TERMINATION_SUCCESS: 'FETCH_TERMINATION_SUCCESS',
  FETCH_TERMINATION_FAILURE: 'FETCH_TERMINATION_FAILURE',

  FETCH_RETIREMENT_LOADING: 'FETCH_RETIREMENT_LOADING',
  FETCH_RETIREMENT_SUCCESS: 'FETCH_RETIREMENT_SUCCESS',
  FETCH_RETIREMENT_FAILURE: 'FETCH_RETIREMENT_FAILURE',

  FETCH_TRANSFER_LOADING: 'FETCH_TRANSFER_LOADING',
  FETCH_TRANSFER_SUCCESS: 'FETCH_TRANSFER_SUCCESS',
  FETCH_TRANSFER_FAILURE: 'FETCH_TRANSFER_FAILURE',
  
  FETCH_QUERY_LOADING: 'FETCH_QUERY_LOADING',
  FETCH_QUERY_SUCCESS: 'FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE: 'FETCH_QUERY_FAILURE',

  FETCH_PAYSLIP_LOADING: 'FETCH_PAYSLIP_LOADING',
  FETCH_PAYSLIP_SUCCESS: 'FETCH_PAYSLIP_SUCCESS',
  FETCH_PAYSLIP_FAILURE: 'FETCH_PAYSLIP_FAILURE',

  FETCH_MEMO_LOADING: 'FETCH_MEMO_LOADING',
  FETCH_MEMO_SUCCESS: 'FETCH_MEMO_SUCCESS',
  FETCH_MEMO_FAILURE: 'FETCH_MEMO_FAILURE',
  
  FETCH_QUOTE_LOADING: 'FETCH_QUOTE_LOADING',
  FETCH_QUOTE_SUCCESS: 'FETCH_QUOTE_SUCCESS',
  FETCH_QUOTE_FAILURE: 'FETCH_QUOTE_FAILURE',

  STORE_PAYROLL_DATA: 'STORE_PAYROLL_DATA',
  STORE_PAYROLL_DATA_REFRESH: 'STORE_PAYROLL_DATA_REFRESH',
};
