export const userConstants = {
  SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',
  SIGN_UP_LOADING: 'USER_SIGN_UP_LOADING',

  SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',
  SIGN_IN_LOADING: 'USER_SIGN_IN_LOADING',

  GOOGLE_SIGNIN_SUCCESS: 'GOOGLE_SIGNIN_SUCCESS',
  GOOGLE_SIGNIN_FAILURE: 'GOOGLE_SIGNIN_FAILURE',
  GOOGLE_SIGNIN_LOADING: 'GOOGLE_SIGNIN_LOADING',
 
  APPLE_SIGNIN_SUCCESS: 'APPLE_SIGNIN_SUCCESS',
  APPLE_SIGNIN_FAILURE: 'APPLE_SIGNIN_FAILURE',
  APPLE_SIGNIN_LOADING: 'APPLE_SIGNIN_LOADING',

  FACEBOOK_SIGNIN_SUCCESS: 'FACEBOOK_SIGNIN_SUCCESS',
  FACEBOOK_SIGNIN_FAILURE: 'FACEBOOK_SIGNIN_FAILURE',
  FACEBOOK_SIGNIN_LOADING: 'FACEBOOK_SIGNIN_LOADING',

  RESET_PASSWORD_SUCCESS: 'USER_RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'USER_RESET_PASSWORD_FAILURE',
  RESET_PASSWORD_LOADING: 'USER_RESET_PASSWORD_LOADING',


  SET_NEW_PASSWORD_SUCCESS: 'SET_NEW_PASSWORD_SUCCESS',
  SET_NEW_PASSWORD_FAILURE: 'SET_NEW_PASSWORD_FAILURE',

  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
  UPDATE_PROFILE_LOADING: 'UPDATE_PROFILE_LOADING',

  COMPLETE_PROFILE_SUCCESS: 'COMPLETE_PROFILE_SUCCESS',
  COMPLETE_PROFILE_LOADING: 'COMPLETE_PROFILE_LOADING',
  COMPLETE_PROFILE_FAILURE: 'COMPLETE_PROFILE_FAILURE',

  PLANS_LOADING: 'PLANS_LOADING',
  PLANS_SUCCESSFUL: 'PLANS_SUCCESSFUL',
  PLANS_FAILURE: 'PLANS_FAILURE',
  PLANS_DATA: 'PLANS_DATA',

  USER_VERIFIED: 'USER_VERIFIED',
  CLEAR_LOGS: 'CLEAR_LOGS',

  LOGOUT: 'LOGOUT',
};
